In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

In [2]:
# Three basic types in Python: integers, floats and strings

# Numbers
##    Integers (ints)
##    Decimals (floats)

In [3]:
10*3 # integer (aka "int")
10/3 # decimal (aka "float") #Note 5 at the end. Finite precision

3.3333333333333335

In [6]:
10**0.5 # Float or Int>
4**0.5  # Float or Int?

2.0

In [10]:
# 1234567**89 # Ints can have lots of digits

In [12]:
# 6/4000000000000000000 # Scientific notation

In [13]:
# Be careful:
(13**0.5)*(13**0.5) # Not exact

12.999999999999998

In [17]:
# Can use variables for numbers
x = 10/3
y = 2/3
x + y

4.0

# Strings (list of characters (letters and numbers))


In [14]:
'Math 118'
len('Math 118')

8

In [16]:
# Can't put '
# 'Don't put apostrophes in'
"Can't put apostrophes" # Use double quotes if you need an apostrophe.

In [18]:
# Can use variables for strings
hi = 'Hello'
x = 'Student'

In [19]:
# 'Hello' + 'Student'
# 'Hello' + ' ' + 'Student
x = 'Hello'
y = ' '
z = 'Student'
x + y + z

'Hello Student'

In [24]:
'ho '*3

'ho ho ho '

In [21]:
# Conversions between types
# 'My grandson is ' + 5
# 'My grandson is ' + str(5)
# "str": int or float to string
# "int": float or string (or int) to int
# "float": int or string (or float) to float

In [22]:
int('123') + 111

234

In [25]:
x = 3
y = '4'
z = '5.6'
# Why errors?
# x + y
# x + int(x+y)
# str(x) + int(y)
# y + float(z)

Object `errors` not found.


In [28]:
# Can find the types of things
type(x)
type(y)
type(float(z))
type(Table.read_table('cones.csv'))
type(abs)

builtin_function_or_method

# Arrays
## List of same type of object

In [35]:
first_four = make_array(1,2,3,4)
first_four
# type(first_four)

array([1, 2, 3, 4])

In [36]:
import numpy as np # standard
np.average(first_four)
np.min(first_four)
np.max(first_four)

4

In [40]:
second_four = make_array(5,6,7,8)
5*second_four
second_four*5
first_four + second_four
first_four * second_four

array([ 5, 12, 21, 32])

In [41]:
s = make_array('ha','he','hi','ho')
s.item(0)
s.item(1)

'he'

# Columns of tables are arrays


In [44]:
nba = Table.read_table('nba_salaries.csv').where('season',2020).drop('season')
nba.num_rows
nba.num_columns
nba.labels


('rank', 'name', 'position', 'team', 'salary')

In [ ]:
# nba.relabeled('salary','$')
# nba

In [49]:
warriors = nba.where('team', 'Golden State Warriors').drop('team').relabeled('salary','$')
# warriors.show(5)

In [50]:
# warriors.select('$')

In [51]:
# warriors.column('$')
# E.g. warriors.columm('$') + 100000

In [54]:
salaries = warriors.column('$')
# Challenge: Find maximum salary and total salary
np.max(salaries) # It's an array
np.sum(salaries)
salaries.item(1)

32742000

In [55]:
np.arange(7)
np.arange(5,11)
np.arange(0,20,2)
np.arange(0,21,2)
np.arange(0,1,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [56]:
warriors.take(0,1,2)

rank,name,position,$
1,Stephen Curry,PG,40231758
13,Klay Thompson,SG,32742000
60,Draymond Green,PF,18539130


In [58]:
# Challenge: Do this with np.arange
# warriors.take(np.arange(3))

In [ ]:
# Review of np.arange
## np.arange(7) [ending number (not included)]
## np.arange(4,9) [starting number and ending number (not included)]
## np.arange(3,11,2) [starting number, ending number (not included), stepsize]